# Generated by Django 5.0.6 on 2025-10-01 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("repeat_count", models.PositiveIntegerField(default=1)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner_token",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("bgm_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "google_sub",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("gender", models.CharField(blank=True, default="", max_length=32)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("is_guest", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("duration_sec", models.PositiveIntegerField(default=10)),
                ("tts_enabled", models.BooleanField(default=True)),
                ("speak_every_sec", models.PositiveIntegerField(default=0)),
                ("countdown_speak_from_sec", models.PositiveIntegerField(default=0)),
                ("cue_beep_last_n_sec", models.PositiveIntegerField(default=0)),
                ("voice_volume", models.FloatField(default=1.0)),
                ("voice_rate", models.FloatField(default=1.0)),
                ("voice_pitch", models.FloatField(default=1.0)),
                ("bgm_volume_override", models.FloatField(blank=True, null=True)),
                (
                    "clock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="timers.clock",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.AddField(
            model_name="clock",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clocks",
                to="timers.userprofile",
            ),
        ),
    ]
